env:
  browser: true
  es6: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {"no-undef": 0, "no-mixed-spaces-and-tabs": 0, "no-global-assign": 0, "no-prototype-builtins": 0}
